name: testingui
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get:
  get_storage:
  image_picker:
  webview_flutter:
  flutter_html:
  firebase_messaging:
  flutter_local_notifications:
  rxdart:
  camera:
  path_provider:
  path:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true
  assets:
    - images/
